add workflow

diff --git a/.github/workflows/run-performance-tests.yml b/.github/workflows/run-performance-tests.yml
--- a/.github/workflows/run-performance-tests.yml
+++ b/.github/workflows/run-performance-tests.yml
@@ -16,38 +16,38 @@ permissions:
   contents: read
 
 jobs:
-  k6-functional:
+  k6-performance-tests:
     runs-on: ubuntu-latest
-    environment: at22 # TODO: No clue what to configure here; ask Andreas
+    environment: yt01 # TODO: No clue what to configure here; ask Andreas
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-    #   - name: OIDC Login to Azure Public Cloud
-    #     uses: azure/login@v2
-    #     with:
-    #       client-id: ${{ vars.ARM_CLIENT_ID }}
-    #       tenant-id: ${{ vars.ARM_TENANT_ID }}
-    #       allow-no-subscriptions: true
+      - name: OIDC Login to Azure Public Cloud
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          allow-no-subscriptions: true
 
-    #   - name: Populate kubeconfig with k6 context
-    #     id: populate_kubeconfig_with_k6_context
-    #     shell: bash
-    #     run: |
-    #       if ! az aks install-cli; then
-    #         echo "Failed to install kubectl CLI"
-    #         exit 1
-    #       fi
+      - name: Populate kubeconfig with k6 context
+        id: populate_kubeconfig_with_k6_context
+        shell: bash
+        run: |
+          if ! az aks install-cli; then
+            echo "Failed to install kubectl CLI"
+            exit 1
+          fi
 
-    #       if ! az aks get-credentials --resource-group k6tests-rg --name k6tests-cluster; then
-    #         echo "Failed to populate kubeconfig"
-    #         exit 1
-    #       fi
+          if ! az aks get-credentials --resource-group k6tests-rg --name k6tests-cluster; then
+            echo "Failed to populate kubeconfig"
+            exit 1
+          fi
 
-    #       if ! kubelogin convert-kubeconfig -l azurecli; then
-    #         echo "Failed to convert kubeconfig"
-    #         exit 1
-    #       fi
+          if ! kubelogin convert-kubeconfig -l azurecli; then
+            echo "Failed to convert kubeconfig"
+            exit 1
+          fi
 
       - name: Generate k8s manifests
         uses: Altinn/altinn-platform/actions/generate-k6-manifests@main
